language: clojure
lein: lein2
script: lein2 do clean, javac, test :all

# Cache our Maven deps to be kind to clojars
cache:
    directories:
    - $HOME/.m2
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
# branches:
#     only:
#         - master
